name: r-artificial_phantasia
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _python_abi3_support
  - _r-mutex
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - binutils_impl_linux-64
  - bleach
  - bleach-with-css
  - brotli-python
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - cpython
  - curl
  - debugpy
  - decorator
  - defusedxml
  - exceptiongroup
  - executing
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fqdn
  - freetype
  - fribidi
  - gcc_impl_linux-64
  - gfortran_impl_linux-64
  - graphite2
  - gsl
  - gxx_impl_linux-64
  - h11
  - h2
  - harfbuzz
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - isoduration
  - jedi
  - jinja2
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kernel-headers_linux-64
  - keyutils
  - krb5
  - lark
  - ld_impl_linux-64
  - lerc
  - libblas
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libfreetype
  - libfreetype6
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - libjpeg-turbo
  - liblapack
  - liblzma
  - libmpdec
  - libnghttp2
  - libopenblas
  - libpng
  - libsanitizer
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - make
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - openssl
  - overrides
  - packaging
  - pandoc
  - pandocfilters
  - pango
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pip
  - pixman
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-gil
  - python-json-logger
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - r-askpass
  - r-assertthat
  - r-backports
  - r-base
  - r-base64enc
  - r-bit
  - r-bit64
  - r-blob
  - r-boot
  - r-broom
  - r-bslib
  - r-cachem
  - r-callr
  - r-caret
  - r-cellranger
  - r-class
  - r-cli
  - r-clipr
  - r-clock
  - r-cluster
  - r-codetools
  - r-colorspace
  - r-commonmark
  - r-conflicted
  - r-cpp11
  - r-crayon
  - r-crul
  - r-curl
  - r-data.table
  - r-dbi
  - r-dbplyr
  - r-diagram
  - r-digest
  - r-dplyr
  - r-dtplyr
  - r-e1071
  - r-ellipsis
  - r-essentials
  - r-evaluate
  - r-fansi
  - r-farver
  - r-fastmap
  - r-fontawesome
  - r-forcats
  - r-foreach
  - r-foreign
  - r-formatr
  - r-fs
  - r-future
  - r-future.apply
  - r-gargle
  - r-generics
  - r-ggplot2
  - r-gistr
  - r-glmnet
  - r-globals
  - r-glue
  - r-googledrive
  - r-googlesheets4
  - r-gower
  - r-groundhog
  - r-gtable
  - r-hardhat
  - r-haven
  - r-hexbin
  - r-highr
  - r-hms
  - r-htmltools
  - r-htmlwidgets
  - r-httpcode
  - r-httpuv
  - r-httr
  - r-ids
  - r-ipred
  - r-irdisplay
  - r-irkernel
  - r-isoband
  - r-iterators
  - r-jquerylib
  - r-jsonlite
  - r-kernsmooth
  - r-knitr
  - r-labeling
  - r-later
  - r-lattice
  - r-lava
  - r-lazyeval
  - r-lifecycle
  - r-listenv
  - r-lobstr
  - r-lubridate
  - r-magrittr
  - r-maps
  - r-mass
  - r-matrix
  - r-memoise
  - r-mgcv
  - r-mime
  - r-modelmetrics
  - r-modelr
  - r-munsell
  - r-nlme
  - r-nnet
  - r-numderiv
  - r-openssl
  - r-parallelly
  - r-patchwork
  - r-pbdzmq
  - r-pillar
  - r-pkgconfig
  - r-plyr
  - r-prettyunits
  - r-proc
  - r-processx
  - r-prodlim
  - r-progress
  - r-progressr
  - r-promises
  - r-proxy
  - r-pryr
  - r-ps
  - r-purrr
  - r-quantmod
  - r-r6
  - r-ragg
  - r-randomforest
  - r-rappdirs
  - r-rbokeh
  - r-rcolorbrewer
  - r-rcpp
  - r-rcppeigen
  - r-readr
  - r-readxl
  - r-recipes
  - r-recommended
  - r-rematch
  - r-rematch2
  - r-repr
  - r-reprex
  - r-reshape2
  - r-rlang
  - r-rmarkdown
  - r-rpart
  - r-rstudioapi
  - r-rvest
  - r-sass
  - r-scales
  - r-selectr
  - r-shape
  - r-shiny
  - r-sourcetools
  - r-sparsevctrs
  - r-spatial
  - r-squarem
  - r-stringi
  - r-stringr
  - r-survival
  - r-sys
  - r-systemfonts
  - r-textshaping
  - r-tibble
  - r-tidyr
  - r-tidyselect
  - r-tidyverse
  - r-timechange
  - r-timedate
  - r-tinytex
  - r-triebeard
  - r-ttr
  - r-tzdb
  - r-urltools
  - r-utf8
  - r-uuid
  - r-vctrs
  - r-viridislite
  - r-vroom
  - r-withr
  - r-xfun
  - r-xml2
  - r-xtable
  - r-xts
  - r-yaml
  - r-zoo
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rfc3987-syntax
  - rpds-py
  - sed
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - stack_data
  - sysroot_linux-64
  - terminado
  - tinycss2
  - tk
  - tktable
  - tomli
  - tornado
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - uri-template
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - yaml
  - zeromq
  - zipp
  - zstandard
  - zstd
